services:
  tg-onedrive-bot:
    build: .
    container_name: tg-onedrive-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RCLONE_CONFIG_FILE=/data/rclone.conf
    volumes:
      - ./data:/data
