name: Guhee Cloud Transfer
on:
  schedule:
    - cron: '*/10 * * * *' # 每10分钟唤醒一次
  workflow_dispatch: # 支持手动触发

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install telethon msal aiohttp
      - name: Run Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
